import { useState } from 'react'

type Format = 'txt' | 'csv' | 'json' | 'hosts' | 'encrypted'
const T = { panel: '#15151d', raised: '#1d1d28', border: '#30303d', text: '#f1f1f5', muted: '#9696a5', accent: '#7c3aed', danger: '#ff6875' }
const input = { width: '100%', boxSizing: 'border-box' as const, background: '#0d0d13', color: T.text, border: `1px solid ${T.border}`, borderRadius: 9, padding: '10px 11px', font: 'inherit', outline: 'none' }
const button = { border: 'none', borderRadius: 9, padding: '9px 13px', background: '#29203f', color: '#d5c7ff', cursor: 'pointer', font: 'inherit', fontWeight: 700 }

export default function ExportDialog({ onClose }: { onClose: () => void }) {
  const [format, setFormat] = useState<Format>('json'); const [path, setPath] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0); const [message, setMessage] = useState<string | null>(null)
  const choose = async () => { const selected = await window.api.chooseExportPath(format); if (selected) setPath(selected) }
  const save = async () => { if (!path) { setMessage('اختر موقع الحفظ أولاً.'); return } if (format === 'encrypted' && (password.length === 0 || password !== confirm)) { setMessage('كلمتا المرور غير متطابقتين أو فارغتين.'); return } setBusy(true); setProgress(20); setMessage('أكمل التحدي لإنشاء التصدير…'); try { const ok = await window.api.createExport({ format, path, password }); if (ok) { setProgress(100); setMessage('تم إنشاء ملف التصدير بنجاح.') } else setMessage('أُلغي التحدي؛ لم يُنشأ ملف.') } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذّر إنشاء التصدير.') } finally { setBusy(false) } }
  return <div className="io-backdrop" onMouseDown={onClose}><style>{`.io-backdrop{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:16px;background:rgba(0,0,0,.74)}@keyframes io-in{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}`}</style><section dir="rtl" onMouseDown={(e) => e.stopPropagation()} style={{ width: 'min(520px, 100%)', background: T.panel, border: `1px solid ${T.border}`, borderRadius: 16, padding: 20, color: T.text, animation: 'io-in 180ms ease-out' }}><header style={{ display: 'flex', justifyContent: 'space-between' }}><div><h2 style={{ margin: 0, fontSize: 20 }}>تصدير البيانات</h2><p style={{ margin: '4px 0 0', color: T.muted, fontSize: 13 }}>يتطلب إنشاء الملف إكمال تحدٍ.</p></div><button type="button" onClick={onClose} style={{ ...button, background: 'transparent', color: T.muted }}>إغلاق</button></header><fieldset style={{ border: 0, padding: 0, margin: '20px 0 0' }}><legend style={{ color: T.muted, fontSize: 13, marginBottom: 8 }}>الصيغة</legend>{(['txt', 'csv', 'json', 'hosts', 'encrypted'] as Format[]).map((id) => <label key={id} style={{ display: 'flex', padding: '8px 0', gap: 8, cursor: 'pointer' }}><input type="radio" checked={format === id} onChange={() => setFormat(id)} /><span>{id === 'encrypted' ? 'نسخة احتياطية مشفّرة (AES-256-GCM)' : `.${id}`}</span></label>)}</fieldset>{format === 'encrypted' && <div style={{ display: 'grid', gap: 9, marginTop: 10 }}><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="كلمة المرور" style={input}/><input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="تأكيد كلمة المرور" style={input}/></div>}<div style={{ display: 'flex', gap: 8, marginTop: 18 }}><input dir="ltr" readOnly value={path} placeholder="اختر موقع الحفظ…" style={input}/><button type="button" onClick={() => void choose()} style={button}>اختيار</button></div>{(busy || progress > 0) && <div style={{ marginTop: 14, height: 6, background: '#0d0d13', borderRadius: 6, overflow: 'hidden' }}><div style={{ width: `${progress}%`, height: '100%', background: T.accent, transition: 'width 260ms ease' }}/></div>}{message && <p role="status" style={{ color: message.includes('غير') ? T.danger : T.muted, fontSize: 13 }}>{message}</p>}<footer style={{ display: 'flex', gap: 8, marginTop: 18 }}><button type="button" disabled={busy} onClick={() => void save()} style={{ ...button, background: T.accent, color: '#fff' }}>تصدير وإكمال التحدي</button><button type="button" onClick={onClose} style={{ ...button, background: 'transparent', color: T.muted }}>إلغاء</button></footer></section></div>
}
