import { useState, type DragEvent } from 'react'
import type { FocusLockImportPreview } from '../env'

type Source = 'file' | 'url' | 'paste' | 'cold-turkey'
const T = { panel: '#15151d', raised: '#1d1d28', border: '#30303d', text: '#f1f1f5', muted: '#9696a5', accent: '#7c3aed', danger: '#ff6875', ok: '#3ddc84' }
const input = { width: '100%', boxSizing: 'border-box' as const, background: '#0d0d13', color: T.text, border: `1px solid ${T.border}`, borderRadius: 9, padding: '10px 11px', font: 'inherit', outline: 'none' }
const button = { border: 'none', borderRadius: 9, padding: '9px 13px', background: '#29203f', color: '#d5c7ff', cursor: 'pointer', font: 'inherit', fontWeight: 700 }

export default function ImportDialog({ onClose, onImported }: { onClose: () => void; onImported: () => void }) {
  const [source, setSource] = useState<Source>('file'); const [value, setValue] = useState(''); const [preview, setPreview] = useState<FocusLockImportPreview | null>(null); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0); const [message, setMessage] = useState<string | null>(null)
  const load = async (kind = source, nextValue = value) => { setBusy(true); setMessage(null); setProgress(15); try { const data = await window.api.previewImport({ kind, value: nextValue }); setPreview(data); setProgress(100) } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذّرت قراءة المصدر.') } finally { setBusy(false) } }
  const browse = async () => { const path = await window.api.chooseImportFile(); if (path) { setValue(path); setSource('file'); await load('file', path) } }
  const drop = async (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); const file = event.dataTransfer.files[0] as (File & { path?: string }) | undefined; if (file?.path) { setValue(file.path); setSource('file'); await load('file', file.path) } else setMessage('تعذّر الوصول إلى مسار الملف.') }
  const commit = async () => { if (!preview) return; setBusy(true); setProgress(20); setMessage('أكمل التحدي لحفظ الاستيراد…'); try { const result = await window.api.commitImport(preview.entries); if (!result) { setMessage('أُلغي التحدي؛ لم يُستورد شيء.'); return } setProgress(100); setMessage(`تمت إضافة ${result.added} نطاق.`); onImported() } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذّر استيراد القائمة.') } finally { setBusy(false) } }
  const labels: Array<[Source, string]> = [['file', 'ملف'], ['url', 'رابط'], ['paste', 'لصق'], ['cold-turkey', 'من تطبيق']]
  return <div className="io-backdrop" onMouseDown={onClose}><style>{`.io-backdrop{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:16px;background:rgba(0,0,0,.74)}@keyframes io-in{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}`}</style><section className="io-dialog" dir="rtl" onMouseDown={(e) => e.stopPropagation()} style={{ width: 'min(760px, 100%)', maxHeight: '90vh', overflowY: 'auto', background: T.panel, border: `1px solid ${T.border}`, borderRadius: 16, padding: 20, color: T.text, animation: 'io-in 180ms ease-out' }}>
    <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', gap: 10 }}><div><h2 style={{ margin: 0, fontSize: 20 }}>استيراد قائمة</h2><p style={{ margin: '4px 0 0', color: T.muted, fontSize: 13 }}>لن تُطبّق التغييرات إلا بعد إكمال التحدي.</p></div><button type="button" onClick={onClose} style={{ ...button, background: 'transparent', color: T.muted }}>إغلاق</button></header>
    <nav style={{ display: 'flex', gap: 5, borderBottom: `1px solid ${T.border}`, marginTop: 18 }}>{labels.map(([id, label]) => <button type="button" key={id} onClick={() => { setSource(id); setPreview(null); setMessage(null) }} style={{ ...button, borderRadius: '8px 8px 0 0', background: source === id ? T.accent : 'transparent', color: source === id ? '#fff' : T.muted }}>{label}</button>)}</nav>
    <div style={{ marginTop: 16 }}>{source === 'file' && <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => void drop(e)} style={{ border: `1px dashed ${T.accent}`, borderRadius: 12, minHeight: 112, display: 'grid', placeItems: 'center', textAlign: 'center', padding: 14, color: T.muted }}><div><div>اسحب ملف TXT / CSV / JSON / HOSTS هنا</div><button type="button" onClick={() => void browse()} style={{ ...button, marginTop: 10 }}>استعراض ملف</button>{value && <div dir="ltr" style={{ marginTop: 8, fontSize: 12, color: T.text }}>{value}</div>}</div></div>}{source === 'url' && <div style={{ display: 'flex', gap: 8 }}><input dir="ltr" value={value} onChange={(e) => setValue(e.target.value)} placeholder="https://example.com/blocklist.txt" style={input}/><button type="button" onClick={() => void load()} style={button}>جلب</button></div>}{source === 'paste' && <div><textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder="ضع نطاقًا في كل سطر…" style={{ ...input, minHeight: 130, resize: 'vertical' }} /><button type="button" onClick={() => void load()} style={{ ...button, marginTop: 8 }}>معاينة اللصق</button></div>}{source === 'cold-turkey' && <div style={{ background: T.raised, borderRadius: 10, padding: 14 }}><strong>Cold Turkey</strong><p style={{ color: T.muted, fontSize: 13 }}>سيُبحث عن ملفات التصدير في C:\ProgramData\Cold Turkey.</p><button type="button" onClick={() => void load()} style={button}>قراءة ملفات Cold Turkey</button></div>}</div>
    {(busy || progress > 0) && <div style={{ marginTop: 14 }}><div style={{ height: 6, borderRadius: 6, background: '#0d0d13', overflow: 'hidden' }}><div style={{ width: `${progress}%`, height: '100%', background: T.accent, transition: 'width 260ms ease' }} /></div></div>}
    {preview && <><div style={{ display: 'flex', gap: 12, marginTop: 16, flexWrap: 'wrap', fontSize: 13 }}><span style={{ color: T.ok }}>{preview.validation.valid.length} صالح</span><span style={{ color: '#f7c948' }}>{preview.validation.duplicates.length} مكرر</span><span style={{ color: T.danger }}>{preview.validation.invalid.length} غير صالح</span></div><div style={{ overflow: 'auto', maxHeight: 220, marginTop: 10, border: `1px solid ${T.border}`, borderRadius: 9 }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}><thead style={{ position: 'sticky', top: 0, background: T.raised }}><tr><th style={{ padding: 8, textAlign: 'right' }}>النطاق (أول 100)</th><th style={{ padding: 8, textAlign: 'right' }}>الفئة</th></tr></thead><tbody>{preview.entries.slice(0, 100).map((entry, index) => <tr key={`${entry.domain}-${index}`}><td dir="ltr" style={{ padding: 8, borderTop: `1px solid ${T.border}` }}>{entry.domain}</td><td style={{ padding: 8, borderTop: `1px solid ${T.border}`, color: T.muted }}>{entry.category ?? '—'}</td></tr>)}</tbody></table></div></>}
    {message && <p role="status" style={{ margin: '12px 0 0', color: T.muted, fontSize: 13 }}>{message}</p>}<footer style={{ display: 'flex', justifyContent: 'flex-start', gap: 8, marginTop: 18 }}><button type="button" disabled={!preview || busy} onClick={() => void commit()} style={{ ...button, background: T.accent, color: '#fff' }}>استيراد وإكمال التحدي</button><button type="button" onClick={onClose} style={{ ...button, background: 'transparent', color: T.muted }}>إلغاء</button></footer>
  </section></div>
}
